---
title: "BIO211 Fall 2015 Student Data"
author: "Emily J. Rollinson"
date: "August 26, 2015"
output: html_document
---

Import the data
```{r}
data<-read.csv('BIO211_StudentData.csv')
```

Week 1, Lecture 2: Plot heights by gender
```{r}
require(ggplot2)
require(plotrix)
require(wesanderson)
require(extrafont)
font_import(pattern="[R/r]oboto")
y
loadfonts(device="win")

#subset female and male data
f<-subset(data, gender=="F")
m<-subset(data, gender=="M")

#calculate se for height
fse<-std.error(f$height)
mse<-std.error(m$height)
ht<-c(mean(f$height), mean(m$height))
se<-c(fse, mse)
g<-c("female", "male")

#Calculate SD for height
fsd<-sd(f$height)
msd<-sd(m$height)
sd<-c(fsd, msd)

#Calculate 95% CI for height
ferror<-qnorm(0.975)*fsd/sqrt(nrow(f))
merror<-qnorm(0.975)*msd/sqrt(nrow(m))
ci<-c(ferror,merror)

df<-data.frame(ht,g,se)

fill<-wes_palette("Zissou")[c(1,4)]

#bar graph
ggplot(df, aes(x=g, y=ht)) + geom_bar(position="dodge", stat="identity", width=.7, aes(fill=factor(g))) + geom_errorbar(aes(ymax=ht+ci, ymin=ht-ci), position="dodge", width=0.2) + xlab("Gender") + ylab("Height (inches)") + theme(text=element_text(size=17))

#dot plot
ggplot(data, aes(x=gender, y=height)) + geom_jitter(aes(color=gender), position=position_jitter(width=0.1), size=4, shape=round) + theme(text=element_text(size=20)) + xlab("Gender") + ylab("Height (inches)") 

#+ scale_y_continuous(limits=c(0,80))

#histograms
ggplot(data, aes(x=height, fill=gender)) + geom_histogram(binwidth=1, alpha=0.5, position="identity")+ theme(text=element_text(size=20)) + xlab("Height (inches)") + ylab("Number of students")

#density plots
ggplot(data, aes(x=height, fill=gender)) + geom_density (alpha=0.3)+ theme(text=element_text(size=20)) + xlab("Height (inches)") + ylab("Number of students")

#adding lines for each mean - first need to create a data frame containing the means

library(plyr)
cdat<-ddply(data, "gender", summarise, rating.mean=mean(height))

ggplot(data, aes(x=height, fill=gender)) + geom_density(alpha=0.3) + geom_vline(data=cdat, aes(xintercept=rating.mean), linetype="dashed", size=1, color="black") + theme(text=element_text(size=20)) + xlab("Height (inches)") + ylab("Proportion of students")

```

Week 2, Lecture 1: Boxplots

```{r}
require(ggplot2)
require(wesanderson)

#subset female and male data
f<-subset(data, gender=="F")
m<-subset(data, gender=="M")


#plotting
fill<-wes_palette("Zissou")[c(1,4)]

#y axis from 0 to 75
ggplot(data, aes(x=gender, y=height)) + geom_boxplot()+ xlab("Gender") + ylab("Height (inches)") + theme(text=element_text(size=17)) + scale_y_continuous(limits = c(0, 75))+ theme(text=element_text(size=40))

#natural y axis
ggplot(data, aes(x=gender, y=height)) + geom_boxplot()+ xlab("Gender") + ylab("Height (inches)") + theme(text=element_text(size=45))

#add points

ggplot(data, aes(x=gender, y=height)) + geom_boxplot()+ xlab("Gender") + ylab("Height (inches)") + theme(text=element_text(size=45)) + geom_point(position=position_jitter(width=0.05), size=5)
```

Week 2, Lecture 2: Confidence interval examples
```{r}
require(ggplot2)
require(wesanderson)

summary(data$height)

#randomly sample 10 students from the data set without replacement

s<-sample(data$height, 10, replace = FALSE)
summary(s)
sample<-data.frame(s)

#plot class and sample histograms
fill<-wes_palette("Zissou")[c(1)]
fill2<-wes_palette("Zissou")[c(4)]
#class
hist(data$height, nclass=10, col=fill, xlab="Heights of all students in BIO211", ylab="Number of students", main="", xlim=c(59,76))

#withdensityfxn
hist(data$height, nclass=20, col=fill, xlab="Heights of all students in BIO211", ylab="Number of students", main="", xlim=c(59,76), prob=TRUE)
lines(density(data$height))

#sample
hist(sample$s, nclass=20, col=fill2, xlab="Heights of ten randomly sampled students in BIO211", ylab="Number of students", main="", xlim=c(58,78))
      
       
#confidence interval on student height

temp<-t.test(sample$s, conf.level=0.99)
temp

#do it again with a random sample of 20

s2<-sample(data$height, 20, replace = FALSE)
summary(s2)
sample2<-data.frame(s2)

       
#confidence interval on student height

temp<-t.test(sample2$s2, conf.level=0.50)
temp

#do it again with a sample of 2 students
s3<-sample(data$height, 2, replace = FALSE)
summary(s3)
sample3<-data.frame(s3)

       
#confidence interval on student height

temp<-t.test(sample3$s3, conf.level=0.20)
temp

```

Week 2, Lecture 2: Plots for students to interpret
```{r}
require(ggplot2)
require(wesanderson)

#Number of siblings versus hours of TV watched
ggplot(data, aes(x=siblings, y=tv)) + geom_point(size=5) + theme_bw() + xlab("BIO211 Students: Number of siblings") + ylab("BIO211 Students: Hours of TV watched") + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + scale_x_continuous(breaks=c(0,1,2,3,4,5,6,7,8))

#Eye colors of students
eyesort<-within(data, eyes<- factor(eyes, levels=names(sort(table(eyes), decreasing=TRUE))))
ggplot(eyesort, aes(x=eyes)) + geom_bar(stat="bin") +xlab("Eye Color") + ylab("Number of BIO211 Students") + theme_bw() + theme(text=element_text(size=18), panel.grid.major=element_blank(), panel.grid.minor = element_blank()) + scale_y_continuous(breaks=(c(0,5,10,15,20,25,30)))

#Siblings of students

ggplot(data, aes(x=siblings)) + geom_bar(stat="bin", binwidth=1, color="black", fill="grey", origin=-0.5) +xlab("Number of Siblings") + ylab("Number of BIO211 Students") + theme_bw() + theme(text=element_text(size=18), panel.grid.major=element_blank(), panel.grid.minor = element_blank()) + scale_y_continuous(breaks=(c(0,5,10,15))) + scale_x_continuous(breaks=(c(0,1,2,3,4,5,6,7,8)))

#Leaf lengths

leaves<-read.csv("Leaf_dataset.csv")
lf<-melt(leaves)


ggplot(lf, aes(x=value)) + geom_bar(stat="bin", binwidth=1, color="black", fill="grey") +xlab("Leaf Length (cm)") + ylab("Number of Leaves") + theme_bw() + theme(text=element_text(size=18), panel.grid.major=element_blank(), panel.grid.minor = element_blank()) + scale_y_continuous(breaks=(c(0,5,10,15,20,25))) + scale_x_continuous(breaks=(c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)))

#Dot plot of leaf lengths per tree
trees<-melt(leaves, id="Group")

ggplot(trees, aes(x=Group, y=value)) + geom_point(size=4) + theme_bw() + xlab("Individual Tree") + ylab("Length of leaves (cm)") + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9))

#box plot of leaf lengths per tree
trees2<-trees[,c(1,3)]
trees2$Group<-as.factor(trees2$Group)
ggplot(trees2, aes(x=Group, y=value)) + geom_boxplot() + theme_bw() + xlab("Individual Tree") + ylab("Length of leaves (cm)") + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank())


+ scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9))

#Dot plot of tv hours men vs women

ggplot(data, aes(x=gender, y=tv)) + geom_point(size=4) + theme_bw() + xlab("Gender") + ylab("Hours of TV Watched") + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 

#box plot of tv hours men vs. women

ggplot(data, aes(x=gender, y=tv)) + geom_boxplot()+ theme_bw() + xlab("Gender") + ylab("Hours of TV Watched") + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 

#scatterplot of height versus hours of TV
ggplot(data, aes(x=height, y=tv)) + geom_point() + theme_bw() + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +xlab("Height of BIO211 Students (inches)") + ylab("Hours of TV Watched")

#import river data for additional plots
require(RCurl)
options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))
raw <- getURL("https://raw.githubusercontent.com/erollinson/Dissertation/master/2012%20Data%20Summary%20with%20Averages%203_3_14%20for%20R.csv") #insert the  raw URL for the data file on github here
plants <- read.csv(text = raw) #read in the github file

#plot river by species richness
ggplot(plants, aes(x=River, y=CountSp)) + geom_bar(stat="identity") + theme_bw() + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +xlab("Name of River") + ylab("Number of Plant Species Nearby")



#importing the second  river data sheet with species origin as a condition (for figures to share axes)

require(RCurl)
options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))
raw <- getURL("https://raw.githubusercontent.com/erollinson/Dissertation/master/2012%20Data%20Summary%20with%20Averages%203_3_14%20for%20R%20by%20origin%20for%20figure%20merge.csv") #insert the  raw URL for the data file on github here
oplants <- read.csv(text = raw) #read in the github file

#Richness by Origin, three streams
ggplot(oplants, aes(x=River, y=SpRich, fill=Origin)) + geom_bar(stat="identity", position="dodge") + theme_bw() + scale_fill_manual(values=c("black", "grey"), name="Species Origin", labels=c("Introduced", "Native")) + theme (text=element_text(size=18), panel.grid.major=element_blank(), panel.grid.minor=element_blank()) + xlab("Name of River") + ylab("Number of Plant Species Nearby") 

#Number of herbaceous plants vs number of woody plants
ggplot(oplants, aes(x=HerbInd, y=WoodInd)) + geom_point() + theme_bw() + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +xlab("Number of Herbaceous Plants in a Site") + ylab("Number of Woody Plants in a Site") + scale_y_continuous(limits=c(0,150), breaks=c(0,25,50,75,100,125,150)) + scale_x_continuous(breaks=c(0,100,200,300,400,500,600))

#natives versus introduced scatterplot
ggplot(plants,aes(x=CountNatSp, y=CountInvSp)) + geom_point(size=4) + theme_bw() + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +xlab("Number of Native Species In a Site") + ylab("Number of Invasive Species In A Site") + scale_y_continuous(breaks=c(0,2,4,6,8,10,12,14))


#PHENOLOGY

fall<-read.csv("Phenology.csv")
fall$Month<-factor(fall$Month, levels=c("Oct", "Nov"))
fall2<-fall[c(1,2,4,5,6,7,8,9,11,12,13,14),]
ggplot(fall2, aes(x=Species, y=Mass, fill=Month)) +geom_bar(stat="identity", position="dodge", color="black") + theme_bw() + theme(text=element_text(size=18), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +xlab("Genus") + ylab("Mass of fallen leaves (g)") + scale_fill_manual(values=c("white", "grey"))

```